import { Prisma } from "@/lib/prisma";

async function seed() {
  await Prisma.pangan.createMany({
    data: [
      {
        id_pangan: 1,
        nama_pangan: "Beras (beras lokal, kualitas unggul, impor)",
        gram: 1000,
        kalori: 3622,
        lemak: 14.5,
        karbohidrat: 775.5,
        protein: 84.75,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "3/4 gelas",
        referensi_gram_berat: 100,
        batas_aman_stok: 1000,
      },
      {
        id_pangan: 2,
        nama_pangan: "Beras ketan",
        gram: 1000,
        kalori: 3605,
        lemak: 15.5,
        karbohidrat: 764.5,
        protein: 77,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "3/4 gelas",
        referensi_gram_berat: 100,
        batas_aman_stok: 800,
      },
      {
        id_pangan: 3,
        nama_pangan: "Jagung basah dengan kulit",
        gram: 1000,
        kalori: 361.2,
        lemak: 3.64,
        karbohidrat: 84.84,
        protein: 11.48,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "1 buah ukuran sedang",
        referensi_gram_berat: 125,
        batas_aman_stok: 500,
      },
      {
        id_pangan: 4,
        nama_pangan: "Jagung pipilan/beras jagung/jagung titi",
        gram: 1000,
        kalori: 3200,
        lemak: 39,
        karbohidrat: 663.3,
        protein: 82.8,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 82,
        batas_aman_stok: 400,
      },
      {
        id_pangan: 5,
        nama_pangan: "Tepung terigu",
        gram: 1000,
        kalori: 3330,
        lemak: 10,
        karbohidrat: 772,
        protein: 90,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "5 sendok makan",
        referensi_gram_berat: 50,
        batas_aman_stok: 600,
      },
      {
        id_pangan: 6,
        nama_pangan: "Padi-padian lainnya",
        gram: 1000,
        kalori: 3570,
        lemak: 9,
        karbohidrat: 762,
        protein: 73,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "1 Kg",
        referensi_gram_berat: 1000,
        batas_aman_stok: 300,
      },
      {
        id_pangan: 7,
        nama_pangan: "Ketela pohon/singkong",
        gram: 1000,
        kalori: 1390,
        lemak: 2.55,
        karbohidrat: 320,
        protein: 8.5,
        id_jenis_pangan: 2,
        id_takaran: 2,
        referensi_urt: "1,5 potong",
        referensi_gram_berat: 120,
        batas_aman_stok: 500,
      },
      {
        id_pangan: 8,
        nama_pangan: "Ketela rambat/ubi jalar",
        gram: 1000,
        kalori: 1252,
        lemak: 3.26,
        karbohidrat: 293.68,
        protein: 11.78,
        id_jenis_pangan: 2,
        id_takaran: 2,
        referensi_urt: "1 biji sedang",
        referensi_gram_berat: 135,
        batas_aman_stok: 400,
      },
      {
        id_pangan: 9,
        nama_pangan: "Sagu (bukan dari ketela pohon)",
        gram: 1000,
        kalori: 3380,
        lemak: 3,
        karbohidrat: 831,
        protein: 6,
        id_jenis_pangan: 2,
        id_takaran: 2,
        referensi_urt: "8 sendok makan",
        referensi_gram_berat: 50,
        batas_aman_stok: 200,
      },
      {
        id_pangan: 10,
        nama_pangan: "Talas/keladi",
        gram: 1000,
        kalori: 1135.4,
        lemak: 3.78,
        karbohidrat: 257.31,
        protein: 15.5,
        id_jenis_pangan: 2,
        id_takaran: 2,
        referensi_urt: "1/2 biji sedang",
        referensi_gram_berat: 125,
        batas_aman_stok: 250,
      },
      {
        id_pangan: 11,
        nama_pangan: "Kentang",
        gram: 1000,
        kalori: 520.8,
        lemak: 1.68,
        karbohidrat: 113.4,
        protein: 17.64,
        id_jenis_pangan: 2,
        id_takaran: 2,
        referensi_urt: "2 buah sedang",
        referensi_gram_berat: 210,
        batas_aman_stok: 500,
      },
      {
        id_pangan: 12,
        nama_pangan: "Gaplek",
        gram: 1000,
        kalori: 3380,
        lemak: 7,
        karbohidrat: 813,
        protein: 15,
        id_jenis_pangan: 2,
        id_takaran: 2,
        referensi_urt: "1 Kg",
        referensi_gram_berat: 1000,
        batas_aman_stok: 150,
      },
      {
        id_pangan: 13,
        nama_pangan: "Umbi-umbian lainnya",
        gram: 1000,
        kalori: 3014.83,
        lemak: 1.75,
        karbohidrat: 432.07,
        protein: 17.5,
        id_jenis_pangan: 2,
        id_takaran: 2,
        referensi_urt: "1 Kg",
        referensi_gram_berat: 1000,
        batas_aman_stok: 200,
      },
      {
        id_pangan: 14,
        nama_pangan: "Ekor kuning",
        gram: 1000,
        kalori: 872,
        lemak: 32,
        karbohidrat: 0,
        protein: 136,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1 potong",
        referensi_gram_berat: 47.8,
        batas_aman_stok: 150,
      },
      {
        id_pangan: 15,
        nama_pangan: "Tongkol",
        gram: 1000,
        kalori: 904,
        lemak: 15,
        karbohidrat: 80,
        protein: 137,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1 ekor sedang",
        referensi_gram_berat: 100,
        batas_aman_stok: 200,
      },
      {
        id_pangan: 16,
        nama_pangan: "Tuna",
        gram: 1000,
        kalori: 904,
        lemak: 49,
        karbohidrat: 0,
        protein: 233,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1 potong sedang",
        referensi_gram_berat: 100,
        batas_aman_stok: 150,
      },
      {
        id_pangan: 17,
        nama_pangan: "Cakalang, dencis",
        gram: 1000,
        kalori: 904,
        lemak: 7,
        karbohidrat: 55,
        protein: 196,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1 potong sedang",
        referensi_gram_berat: 100,
        batas_aman_stok: 180,
      },
      {
        id_pangan: 18,
        nama_pangan: "Tenggiri",
        gram: 1000,
        kalori: 904,
        lemak: 36,
        karbohidrat: 0,
        protein: 136,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1 potong sedang",
        referensi_gram_berat: 100,
        batas_aman_stok: 180,
      },
      {
        id_pangan: 19,
        nama_pangan: "Selar",
        gram: 1000,
        kalori: 480,
        lemak: 10.56,
        karbohidrat: 0,
        protein: 90.24,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 90,
        batas_aman_stok: 120,
      },
      {
        id_pangan: 20,
        nama_pangan: "Kembung, lema/tatare, banyara/banyara",
        gram: 1000,
        kalori: 824,
        lemak: 8,
        karbohidrat: 0,
        protein: 176,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1/3 ekor sedang",
        referensi_gram_berat: 45,
        batas_aman_stok: 100,
      },
      {
        id_pangan: 21,
        nama_pangan: "Teri basah",
        gram: 1000,
        kalori: 740,
        lemak: 14,
        karbohidrat: 41,
        protein: 103,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1 sdm",
        referensi_gram_berat: 30,
        batas_aman_stok: 80,
      },
      {
        id_pangan: 22,
        nama_pangan: "Bandeng",
        gram: 1000,
        kalori: 900,
        lemak: 14,
        karbohidrat: 0,
        protein: 170,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1 potong",
        referensi_gram_berat: 82,
        batas_aman_stok: 150,
      },
      {
        id_pangan: 23,
        nama_pangan: "Gabus",
        gram: 1000,
        kalori: 477.4,
        lemak: 6.2,
        karbohidrat: 22.94,
        protein: 76.88,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1 ekor",
        referensi_gram_berat: 212.2,
        batas_aman_stok: 120,
      },
      {
        id_pangan: 24,
        nama_pangan: "Mujair",
        gram: 1000,
        kalori: 712,
        lemak: 8,
        karbohidrat: 0,
        protein: 149.68,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1/3 ekor sedang",
        referensi_gram_berat: 30,
        batas_aman_stok: 120,
      },
      {
        id_pangan: 25,
        nama_pangan: "Mas",
        gram: 1000,
        kalori: 688,
        lemak: 20,
        karbohidrat: 0,
        protein: 160,
        id_jenis_pangan: 15,
        id_takaran: 15,
        referensi_urt: "1/3 ekor sedang",
        referensi_gram_berat: 45,
        batas_aman_stok: 120,
      },
    ],
  });
}

seed()
  .then(() => {
    console.log("✅ Seed data pangan selesai.");
  })
  .catch((err: unknown) => {
    console.error(`❌ Terjadi kesalahan saat seeding pangan: ${err}`);
    process.exit(1);
  });