import { Prisma } from "@/lib/prisma";

async function seed() {
  await Prisma.pangan.createMany({
    data: [
      {
        id_pangan: 1,
        nama_pangan: "Beras (beras lokal, kualitas unggul, impor)",
        gram: 1000.0,
        kalori: 3622.0,
        lemak: 14.5,
        karbohidrat: 775.5,
        protein: 84.75,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "3/4 gelas",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 2,
        nama_pangan: "Beras ketan",
        gram: 1000.0,
        kalori: 3605.0,
        lemak: 15.5,
        karbohidrat: 764.5,
        protein: 77.0,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "3/4 gelas",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 3,
        nama_pangan: "Jagung basah dengan kulit",
        gram: 1000.0,
        kalori: 361.2,
        lemak: 3.64,
        karbohidrat: 84.84,
        protein: 11.48,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "1 buah ukuran sedang",
        referensi_gram_berat: 125,
      },
      {
        id_pangan: 4,
        nama_pangan: "Jagung pipilan/beras jagung/jagung titi",
        gram: 1000.0,
        kalori: 3200.0,
        lemak: 39.0,
        karbohidrat: 663.3,
        protein: 82.8,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 82,
      },
      {
        id_pangan: 5,
        nama_pangan: "Tepung terigu",
        gram: 1000.0,
        kalori: 3330.0,
        lemak: 10.0,
        karbohidrat: 772.0,
        protein: 90.0,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "5 sendok makan",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 6,
        nama_pangan: "Padi-padian lainnya",
        gram: 1000.0,
        kalori: 3570.0,
        lemak: 9.0,
        karbohidrat: 762.0,
        protein: 73.0,
        id_jenis_pangan: 1,
        id_takaran: 1,
        referensi_urt: "1 Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 7,
        nama_pangan: "Ketela pohon/singkong",
        gram: 1000.0,
        kalori: 1309.0,
        lemak: 2.55,
        karbohidrat: 312.8,
        protein: 8.5,
        id_jenis_pangan: 2,
        id_takaran: 1,
        referensi_urt: "1,5 potong",
        referensi_gram_berat: 120,
      },
      {
        id_pangan: 8,
        nama_pangan: "Ketela rambat/ubi jalar",
        gram: 1000.0,
        kalori: 1252.0,
        lemak: 3.26,
        karbohidrat: 293.68,
        protein: 11.78,
        id_jenis_pangan: 2,
        id_takaran: 1,
        referensi_urt: "1 biji sedang",
        referensi_gram_berat: 135,
      },
      {
        id_pangan: 9,
        nama_pangan: "Sagu (bukan dari ketela pohon)",
        gram: 1000.0,
        kalori: 3380.0,
        lemak: 3.0,
        karbohidrat: 831.0,
        protein: 6.0,
        id_jenis_pangan: 2,
        id_takaran: 1,
        referensi_urt: "8 sendok makan",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 10,
        nama_pangan: "Talas/keladi",
        gram: 1000.0,
        kalori: 1135.4,
        lemak: 3.78,
        karbohidrat: 257.31,
        protein: 15.5,
        id_jenis_pangan: 2,
        id_takaran: 1,
        referensi_urt: "1/2 biji sedang",
        referensi_gram_berat: 125,
      },
      {
        id_pangan: 11,
        nama_pangan: "Kentang",
        gram: 1000.0,
        kalori: 520.8,
        lemak: 1.68,
        karbohidrat: 113.4,
        protein: 17.64,
        id_jenis_pangan: 2,
        id_takaran: 1,
        referensi_urt: "2 buah sedang",
        referensi_gram_berat: 210,
      },
      {
        id_pangan: 12,
        nama_pangan: "Gaplek",
        gram: 1000.0,
        kalori: 3380.0,
        lemak: 7.0,
        karbohidrat: 813.0,
        protein: 15.0,
        id_jenis_pangan: 2,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 13,
        nama_pangan: "Umbi-umbian lainnya",
        gram: 1000.0,
        kalori: 3014.83,
        lemak: 1.75,
        karbohidrat: 432.27,
        protein: 13.0,
        id_jenis_pangan: 2,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 14,
        nama_pangan: "Ekor kuning",
        gram: 1000.0,
        kalori: 872.0,
        lemak: 32.0,
        karbohidrat: 0.0,
        protein: 136.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 potong",
        referensi_gram_berat: 47.8,
      },
      {
        id_pangan: 15,
        nama_pangan: "Tongkol",
        gram: 1000.0,
        kalori: 904.0,
        lemak: 15.0,
        karbohidrat: 80.0,
        protein: 137.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 ekor sedang",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 16,
        nama_pangan: "Tuna",
        gram: 1000.0,
        kalori: 904.0,
        lemak: 49.0,
        karbohidrat: 0.0,
        protein: 233.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 potong sedang",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 17,
        nama_pangan: "Cakalang, dencis",
        gram: 1000.0,
        kalori: 904.0,
        lemak: 7.0,
        karbohidrat: 55.0,
        protein: 196.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 potong sedang",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 18,
        nama_pangan: "Tenggiri",
        gram: 1000.0,
        kalori: 904.0,
        lemak: 36.0,
        karbohidrat: 0.0,
        protein: 136.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 potong sedang",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 19,
        nama_pangan: "Selar",
        gram: 1000.0,
        kalori: 480.0,
        lemak: 10.56,
        karbohidrat: 0.0,
        protein: 90.24,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 90,
      },
      {
        id_pangan: 20,
        nama_pangan: "Kembung, lema/tatare, banyar/banyara",
        gram: 1000.0,
        kalori: 824.0,
        lemak: 8.0,
        karbohidrat: 0.0,
        protein: 176.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1/3 ekor sedang",
        referensi_gram_berat: 45,
      },
      {
        id_pangan: 21,
        nama_pangan: "Teri basah",
        gram: 1000.0,
        kalori: 740.0,
        lemak: 14.0,
        karbohidrat: 41.0,
        protein: 103.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 sdm",
        referensi_gram_berat: 15,
      },
      {
        id_pangan: 22,
        nama_pangan: "Bandeng",
        gram: 1000.0,
        kalori: 1032.0,
        lemak: 38.4,
        karbohidrat: 0.0,
        protein: 160.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 potong",
        referensi_gram_berat: 82,
      },
      {
        id_pangan: 23,
        nama_pangan: "Gabus",
        gram: 1000.0,
        kalori: 477.4,
        lemak: 6.2,
        karbohidrat: 22.94,
        protein: 76.88,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 ekor",
        referensi_gram_berat: 212.2,
      },
      {
        id_pangan: 24,
        nama_pangan: "Mujair",
        gram: 1000.0,
        kalori: 712.0,
        lemak: 8.0,
        karbohidrat: 0.0,
        protein: 149.6,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1/3 ekor sedang",
        referensi_gram_berat: 30,
      },
      {
        id_pangan: 25,
        nama_pangan: "Mas",
        gram: 1000.0,
        kalori: 688.0,
        lemak: 20.0,
        karbohidrat: 0.0,
        protein: 160.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1/3 ekor sedang",
        referensi_gram_berat: 45,
      },
      {
        id_pangan: 26,
        nama_pangan: "Nila",
        gram: 1000.0,
        kalori: 688.0,
        lemak: 10.0,
        karbohidrat: 0.0,
        protein: 187.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 27,
        nama_pangan: "Lele",
        gram: 1000.0,
        kalori: 477.4,
        lemak: 6.2,
        karbohidrat: 22.94,
        protein: 76.88,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1/3 ekor sedang",
        referensi_gram_berat: 40,
      },
      {
        id_pangan: 28,
        nama_pangan: "Kakap",
        gram: 1000.0,
        kalori: 736.0,
        lemak: 5.6,
        karbohidrat: 0.0,
        protein: 160.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1/3 ekor besar",
        referensi_gram_berat: 35,
      },
      {
        id_pangan: 29,
        nama_pangan: "Baronang",
        gram: 1000.0,
        kalori: 1200.0,
        lemak: 53.0,
        karbohidrat: 4.0,
        protein: 165.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 85,
      },
      {
        id_pangan: 30,
        nama_pangan: "Patin",
        gram: 1000.0,
        kalori: 477.4,
        lemak: 6.2,
        karbohidrat: 22.94,
        protein: 76.88,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 110,
      },
      {
        id_pangan: 31,
        nama_pangan: "Bawal",
        gram: 1000.0,
        kalori: 960.0,
        lemak: 17.0,
        karbohidrat: 0.0,
        protein: 190.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 ekor",
        referensi_gram_berat: 132.2,
      },
      {
        id_pangan: 32,
        nama_pangan: "Gurame",
        gram: 1000.0,
        kalori: 712.0,
        lemak: 8.0,
        karbohidrat: 0.0,
        protein: 149.6,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 110,
      },
      {
        id_pangan: 33,
        nama_pangan: "Ikan segar/basah lainnya",
        gram: 1000.0,
        kalori: 904.0,
        lemak: 36.0,
        karbohidrat: 0.0,
        protein: 136.0,
        id_jenis_pangan: 15,
        id_takaran: 1,
        referensi_urt: "1 Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 34,
        nama_pangan: "Udang, lobster",
        gram: 1000.0,
        kalori: 618.8,
        lemak: 1.36,
        karbohidrat: 0.68,
        protein: 142.8,
        id_jenis_pangan: 16,
        id_takaran: 1,
        referensi_urt: "5 ekor sedang ",
        referensi_gram_berat: 35,
      },
      {
        id_pangan: 35,
        nama_pangan: "Cumi-cumi, sotong, gurita",
        gram: 1000.0,
        kalori: 750.0,
        lemak: 7.0,
        karbohidrat: 1.0,
        protein: 161.0,
        id_jenis_pangan: 16,
        id_takaran: 1,
        referensi_urt: "1 ekor kecil",
        referensi_gram_berat: 45,
      },
      {
        id_pangan: 36,
        nama_pangan: "Ketam, kepiting, rajungan",
        gram: 1000.0,
        kalori: 679.5,
        lemak: 17.1,
        karbohidrat: 63.5,
        protein: 62.1,
        id_jenis_pangan: 16,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 37,
        nama_pangan: "Kerang, siput, bekicot, remis",
        gram: 1000.0,
        kalori: 1010.0,
        lemak: 26.0,
        karbohidrat: 39.0,
        protein: 144.0,
        id_jenis_pangan: 16,
        id_takaran: 1,
        referensi_urt: "1/2 gelas",
        referensi_gram_berat: 90,
      },
      {
        id_pangan: 38,
        nama_pangan: "Udang dan hewan air lainnya yang segar lainnya",
        gram: 1000.0,
        kalori: 552.2,
        lemak: 8.3,
        karbohidrat: 8.1,
        protein: 108.6,
        id_jenis_pangan: 16,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 39,
        nama_pangan: "Kembung diawetkan/peda",
        gram: 100.0,
        kalori: 140.4,
        lemak: 3.6,
        karbohidrat: 0.0,
        protein: 25.2,
        id_jenis_pangan: 17,
        id_takaran: 2,
        referensi_urt: "Ons",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 40,
        nama_pangan: "Tenggiri diawetkan",
        gram: 100.0,
        kalori: 135.1,
        lemak: 1.05,
        karbohidrat: 0.0,
        protein: 29.4,
        id_jenis_pangan: 17,
        id_takaran: 2,
        referensi_urt: "Ons",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 41,
        nama_pangan: "Tongkol, tuna, cakalang, dencis, ikan kayu diawetkan",
        gram: 100.0,
        kalori: 138.6,
        lemak: 1.54,
        karbohidrat: 3.85,
        protein: 25.55,
        id_jenis_pangan: 17,
        id_takaran: 2,
        referensi_urt: "1 potong sedang",
        referensi_gram_berat: 20,
      },
      {
        id_pangan: 42,
        nama_pangan: "Teri diawetkan",
        gram: 100.0,
        kalori: 230.5,
        lemak: 2.52,
        karbohidrat: 0.45,
        protein: 48.65,
        id_jenis_pangan: 17,
        id_takaran: 2,
        referensi_urt: "1 sendok makan",
        referensi_gram_berat: 20,
      },
      {
        id_pangan: 43,
        nama_pangan: "Selar diawetkan",
        gram: 100.0,
        kalori: 145.5,
        lemak: 2.62,
        karbohidrat: 0.0,
        protein: 28.5,
        id_jenis_pangan: 17,
        id_takaran: 2,
        referensi_urt: "1 ekor",
        referensi_gram_berat: 20,
      },
      {
        id_pangan: 44,
        nama_pangan: "Sepat diawetkan",
        gram: 100.0,
        kalori: 216.8,
        lemak: 10.5,
        karbohidrat: 0.0,
        protein: 28.5,
        id_jenis_pangan: 17,
        id_takaran: 2,
        referensi_urt: "1 potong sedang",
        referensi_gram_berat: 20,
      },
      {
        id_pangan: 45,
        nama_pangan: "Bandeng diawetkan",
        gram: 100.0,
        kalori: 296.0,
        lemak: 20.3,
        karbohidrat: 11.3,
        protein: 17.1,
        id_jenis_pangan: 17,
        id_takaran: 2,
        referensi_urt: "Ons",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 46,
        nama_pangan: "Gabus diawetkan",
        gram: 100.0,
        kalori: 233.6,
        lemak: 3.2,
        karbohidrat: 0.0,
        protein: 46.4,
        id_jenis_pangan: 17,
        id_takaran: 2,
        referensi_urt: "1 ekor kecil",
        referensi_gram_berat: 10,
      },
      {
        id_pangan: 47,
        nama_pangan: "Ikan dalam kaleng (sardencis, tuna dalam kaleng, dsb)",
        gram: 100.0,
        kalori: 338.0,
        lemak: 27.0,
        karbohidrat: 0.0,
        protein: 21.1,
        id_jenis_pangan: 17,
        id_takaran: 2,
        referensi_urt: "1/2 potong",
        referensi_gram_berat: 35,
      },
      {
        id_pangan: 48,
        nama_pangan: "Ikan diawetkan lainnya",
        gram: 100.0,
        kalori: 305.0,
        lemak: 8.9,
        karbohidrat: 10.86,
        protein: 43.62,
        id_jenis_pangan: 17,
        id_takaran: 2,
        referensi_urt: "Ons",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 49,
        nama_pangan: "Udang (ebi, rebon)",
        gram: 100.0,
        kalori: 265.5,
        lemak: 2.07,
        karbohidrat: 1.6,
        protein: 56.16,
        id_jenis_pangan: 18,
        id_takaran: 2,
        referensi_urt: "2 sendok makan",
        referensi_gram_berat: 10,
      },
      {
        id_pangan: 50,
        nama_pangan: "Cumi-cumi, sotong, gurita diawetkan",
        gram: 100.0,
        kalori: 265.5,
        lemak: 2.07,
        karbohidrat: 1.6,
        protein: 56.16,
        id_jenis_pangan: 18,
        id_takaran: 2,
        referensi_urt: "2 sendok makan",
        referensi_gram_berat: 10,
      },
      {
        id_pangan: 51,
        nama_pangan: "Udang dan hewan air lainnya yang diawetkan",
        gram: 100.0,
        kalori: 357.0,
        lemak: 10.0,
        karbohidrat: 25.6,
        protein: 41.1,
        id_jenis_pangan: 18,
        id_takaran: 2,
        referensi_urt: "Ons",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 52,
        nama_pangan: "Daging sapi",
        gram: 1000.0,
        kalori: 2070.0,
        lemak: 140.0,
        karbohidrat: 0.0,
        protein: 188.0,
        id_jenis_pangan: 19,
        id_takaran: 1,
        referensi_urt: "1 potong sedang ",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 53,
        nama_pangan: "Daging kambing, domba/biri-biri",
        gram: 1000.0,
        kalori: 1540.0,
        lemak: 92.0,
        karbohidrat: 0.0,
        protein: 166.0,
        id_jenis_pangan: 19,
        id_takaran: 1,
        referensi_urt: "1 potong sedang ",
        referensi_gram_berat: 40,
      },
      {
        id_pangan: 54,
        nama_pangan: "Daging babi",
        gram: 1000.0,
        kalori: 4165.0,
        lemak: 400.0,
        karbohidrat: 0.0,
        protein: 130.0,
        id_jenis_pangan: 19,
        id_takaran: 1,
        referensi_urt: "1 potong sedang ",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 55,
        nama_pangan: "Daging ayam ras",
        gram: 1000.0,
        kalori: 3020.0,
        lemak: 250.0,
        karbohidrat: 0.0,
        protein: 182.0,
        id_jenis_pangan: 19,
        id_takaran: 1,
        referensi_urt: "1 potong sedang ",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 56,
        nama_pangan: "Daging ayam kampung",
        gram: 1000.0,
        kalori: 3020.0,
        lemak: 250.0,
        karbohidrat: 0.0,
        protein: 182.0,
        id_jenis_pangan: 19,
        id_takaran: 1,
        referensi_urt: "1 potong sedang ",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 57,
        nama_pangan: "Daging segar lainnya",
        gram: 1000.0,
        kalori: 2050.0,
        lemak: 148.0,
        karbohidrat: 0.0,
        protein: 171.0,
        id_jenis_pangan: 19,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 58,
        nama_pangan: "Daging diawetkan (sosis, abon, nugget, lainnya)",
        gram: 1000.0,
        kalori: 3385.69,
        lemak: 423.0,
        karbohidrat: 23.0,
        protein: 145.0,
        id_jenis_pangan: 20,
        id_takaran: 1,
        referensi_urt: "1/2 potong",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 59,
        nama_pangan: "Tetelan, sandung lamur",
        gram: 1000.0,
        kalori: 1280.0,
        lemak: 65.0,
        karbohidrat: 8.0,
        protein: 155.3,
        id_jenis_pangan: 21,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 60,
        nama_pangan: "Lainnya (hati, jeroan, iga, kaki, buntut, kepala, dsb)",
        gram: 1000.0,
        kalori: 1189.58,
        lemak: 65.0,
        karbohidrat: 8.0,
        protein: 155.3,
        id_jenis_pangan: 21,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 61,
        nama_pangan: "Telur ayam ras",
        gram: 60.0,
        kalori: 82.24,
        lemak: 5.77,
        karbohidrat: 0.37,
        protein: 6.62,
        id_jenis_pangan: 5,
        id_takaran: 3,
        referensi_urt: "1 Butir",
        referensi_gram_berat: 60,
      },
      {
        id_pangan: 62,
        nama_pangan: "Telur ayam kampung",
        gram: 50.0,
        kalori: 68.9,
        lemak: 5.32,
        karbohidrat: 0.28,
        protein: 4.52,
        id_jenis_pangan: 5,
        id_takaran: 3,
        referensi_urt: "1 Butir",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 63,
        nama_pangan: "Telur itik/telur itik manila",
        gram: 70.0,
        kalori: 125.4,
        lemak: 10.18,
        karbohidrat: 0.0,
        protein: 7.76,
        id_jenis_pangan: 5,
        id_takaran: 3,
        referensi_urt: "1 Butir",
        referensi_gram_berat: 70,
      },
      {
        id_pangan: 64,
        nama_pangan: "Telur lainnya (telur puyuh, telur asin mentah maupun matang, telur penyu, telur angsa, dsb)",
        gram: 43.6,
        kalori: 64.2,
        lemak: 0.0,
        karbohidrat: 0.0,
        protein: 4.83,
        id_jenis_pangan: 5,
        id_takaran: 3,
        referensi_urt: "1 Butir",
        referensi_gram_berat: 43.6,
      },
      {
        id_pangan: 65,
        nama_pangan: "Susu cair pabrik",
        gram: 200.0,
        kalori: 122.0,
        lemak: 7.0,
        karbohidrat: 8.6,
        protein: 6.4,
        id_jenis_pangan: 5,
        id_takaran: 12,
        referensi_urt: "Kotak",
        referensi_gram_berat: 200,
      },
      {
        id_pangan: 66,
        nama_pangan: "Susu kental manis",
        gram: 397.0,
        kalori: 1333.9,
        lemak: 39.7,
        karbohidrat: 218.35,
        protein: 32.55,
        id_jenis_pangan: 5,
        id_takaran: 13,
        referensi_urt: "Kaleng",
        referensi_gram_berat: 397,
      },
      {
        id_pangan: 67,
        nama_pangan: "Susu bubuk",
        gram: 1000.0,
        kalori: 5090.0,
        lemak: 300.0,
        karbohidrat: 362.0,
        protein: 246.0,
        id_jenis_pangan: 5,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 68,
        nama_pangan: "Susu bubuk bayi",
        gram: 1000.0,
        kalori: 1672.0,
        lemak: 36.0,
        karbohidrat: 262.0,
        protein: 76.0,
        id_jenis_pangan: 5,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 69,
        nama_pangan: "Susu lainnya dan hasil lain dari susu",
        gram: 100.0,
        kalori: 488.0,
        lemak: 2.5,
        karbohidrat: 4.0,
        protein: 3.3,
        id_jenis_pangan: 5,
        id_takaran: 2,
        referensi_urt: "Ons",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 70,
        nama_pangan: "Bayam",
        gram: 1000.0,
        kalori: 113.6,
        lemak: 2.84,
        karbohidrat: 20.59,
        protein: 6.39,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 ikat",
        referensi_gram_berat: 200,
      },
      {
        id_pangan: 71,
        nama_pangan: "Kangkung",
        gram: 1000.0,
        kalori: 168.0,
        lemak: 4.2,
        karbohidrat: 23.4,
        protein: 20.4,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 ikat",
        referensi_gram_berat: 200,
      },
      {
        id_pangan: 72,
        nama_pangan: "Kol/kubis",
        gram: 1000.0,
        kalori: 180.0,
        lemak: 1.5,
        karbohidrat: 39.75,
        protein: 10.5,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 mangkok dicincang",
        referensi_gram_berat: 117,
      },
      {
        id_pangan: 73,
        nama_pangan: "Sawi putih (petsai)",
        gram: 1000.0,
        kalori: 66.0,
        lemak: 1.5,
        karbohidrat: 10.8,
        protein: 6.3,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 mangkok",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 74,
        nama_pangan: "Sawi hijau",
        gram: 1000.0,
        kalori: 191.4,
        lemak: 2.61,
        karbohidrat: 34.8,
        protein: 20.01,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 ikat",
        referensi_gram_berat: 200,
      },
      {
        id_pangan: 75,
        nama_pangan: "Buncis",
        gram: 1000.0,
        kalori: 306.0,
        lemak: 2.7,
        karbohidrat: 64.8,
        protein: 21.6,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 mangkok",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 76,
        nama_pangan: "Kacang panjang",
        gram: 1000.0,
        kalori: 276.0,
        lemak: 4.6,
        karbohidrat: 47.8,
        protein: 27.6,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 ikat",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 77,
        nama_pangan: "Tomat sayur, tomat ceri",
        gram: 1000.0,
        kalori: 190.0,
        lemak: 2.9,
        karbohidrat: 39.9,
        protein: 9.5,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 buah",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 78,
        nama_pangan: "Wortel",
        gram: 1000.0,
        kalori: 288.0,
        lemak: 4.8,
        karbohidrat: 63.2,
        protein: 8.0,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 buah besar",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 79,
        nama_pangan: "Mentimun",
        gram: 1000.0,
        kalori: 68.7,
        lemak: 1.21,
        karbohidrat: 13.67,
        protein: 3.22,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 buah kecil",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 80,
        nama_pangan: "Daun ketela pohon/daun singkong",
        gram: 1000.0,
        kalori: 635.1,
        lemak: 10.44,
        karbohidrat: 113.1,
        protein: 59.16,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 81,
        nama_pangan: "Terong",
        gram: 1000.0,
        kalori: 373.1,
        lemak: 5.88,
        karbohidrat: 71.44,
        protein: 15.32,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 buah",
        referensi_gram_berat: 225,
      },
      {
        id_pangan: 82,
        nama_pangan: "Tauge",
        gram: 1000.0,
        kalori: 340.0,
        lemak: 12.0,
        karbohidrat: 43.0,
        protein: 37.0,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 83,
        nama_pangan: "Labu, labu siam, labu parang",
        gram: 1000.0,
        kalori: 191.7,
        lemak: 1.58,
        karbohidrat: 45.61,
        protein: 6.08,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 84,
        nama_pangan: "Bahan sayur sop/cap cay/kimlo (paket)",
        gram: 500.0,
        kalori: 67.5,
        lemak: 5.0,
        karbohidrat: 2.5,
        protein: 3.25,
        id_jenis_pangan: 6,
        id_takaran: 14,
        referensi_urt: "Bungkus",
        referensi_gram_berat: 500,
      },
      {
        id_pangan: 85,
        nama_pangan: "Bahan sayur asam/lodeh (paket)",
        gram: 600.0,
        kalori: 116.0,
        lemak: 2.4,
        karbohidrat: 20.0,
        protein: 2.8,
        id_jenis_pangan: 6,
        id_takaran: 14,
        referensi_urt: "Bungkus",
        referensi_gram_berat: 600,
      },
      {
        id_pangan: 86,
        nama_pangan: "Nangka muda",
        gram: 1000.0,
        kalori: 408.0,
        lemak: 3.2,
        karbohidrat: 90.4,
        protein: 16.0,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 87,
        nama_pangan: "Pepaya muda",
        gram: 1000.0,
        kalori: 197.6,
        lemak: 0.76,
        karbohidrat: 37.24,
        protein: 15.96,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 bungkus",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 88,
        nama_pangan: "Jengkol",
        gram: 1000.0,
        kalori: 1260.0,
        lemak: 0.9,
        karbohidrat: 259.2,
        protein: 56.7,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 porsi",
        referensi_gram_berat: 125,
      },
      {
        id_pangan: 89,
        nama_pangan: "Bawang merah",
        gram: 100.0,
        kalori: 35.1,
        lemak: 0.27,
        karbohidrat: 0.18,
        protein: 1.35,
        id_jenis_pangan: 6,
        id_takaran: 2,
        referensi_urt: "1 buah",
        referensi_gram_berat: 8,
      },
      {
        id_pangan: 90,
        nama_pangan: "Bawang putih",
        gram: 100.0,
        kalori: 83.6,
        lemak: 0.18,
        karbohidrat: 20.33,
        protein: 3.96,
        id_jenis_pangan: 6,
        id_takaran: 2,
        referensi_urt: "1 buah",
        referensi_gram_berat: 8,
      },
      {
        id_pangan: 91,
        nama_pangan: "Bawang bombay",
        gram: 100.0,
        kalori: 43.0,
        lemak: 0.2,
        karbohidrat: 10.3,
        protein: 1.4,
        id_jenis_pangan: 6,
        id_takaran: 2,
        referensi_urt: "1 buah sedang",
        referensi_gram_berat: 150,
      },
      {
        id_pangan: 92,
        nama_pangan: "Cabe merah",
        gram: 1000.0,
        kalori: 264.0,
        lemak: 2.6,
        karbohidrat: 62.1,
        protein: 8.5,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 buah sedang",
        referensi_gram_berat: 8,
      },
      {
        id_pangan: 93,
        nama_pangan: "Cabe hijau",
        gram: 1000.0,
        kalori: 189.0,
        lemak: 2.5,
        karbohidrat: 42.6,
        protein: 5.7,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 buah sedang",
        referensi_gram_berat: 5,
      },
      {
        id_pangan: 94,
        nama_pangan: "Cabe rawit",
        gram: 1000.0,
        kalori: 876.0,
        lemak: 20.4,
        karbohidrat: 169.22,
        protein: 40.0,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "1 buah sedang",
        referensi_gram_berat: 3.5,
      },
      {
        id_pangan: 95,
        nama_pangan: "Sayur-sayuran lainnya",
        gram: 1000.0,
        kalori: 110.15,
        lemak: 5.9,
        karbohidrat: 48.82,
        protein: 24.96,
        id_jenis_pangan: 6,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 96,
        nama_pangan: "Kacang tanah tanpa Kulit",
        gram: 1000.0,
        kalori: 4520.0,
        lemak: 428.0,
        karbohidrat: 211.0,
        protein: 253.0,
        id_jenis_pangan: 7,
        id_takaran: 1,
        referensi_urt: "2 sendok makan",
        referensi_gram_berat: 20,
      },
      {
        id_pangan: 97,
        nama_pangan: "Kacang kedele",
        gram: 1000.0,
        kalori: 3810.0,
        lemak: 167.0,
        karbohidrat: 249.0,
        protein: 404.0,
        id_jenis_pangan: 7,
        id_takaran: 1,
        referensi_urt: "2,5 sendok makan",
        referensi_gram_berat: 25,
      },
      {
        id_pangan: 98,
        nama_pangan: "Kacang lainnya",
        gram: 1000.0,
        kalori: 2988.23,
        lemak: 40.06,
        karbohidrat: 411.33,
        protein: 201.31,
        id_jenis_pangan: 7,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 99,
        nama_pangan: "Tahu",
        gram: 1000.0,
        kalori: 800.0,
        lemak: 47.0,
        karbohidrat: 8.0,
        protein: 109.0,
        id_jenis_pangan: 7,
        id_takaran: 1,
        referensi_urt: "2 potong sedang",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 100,
        nama_pangan: "Tempe",
        gram: 1000.0,
        kalori: 1430.0,
        lemak: 55.0,
        karbohidrat: 114.0,
        protein: 120.0,
        id_jenis_pangan: 7,
        id_takaran: 1,
        referensi_urt: "1 potong",
        referensi_gram_berat: 25,
      },
      {
        id_pangan: 101,
        nama_pangan: "Oncom",
        gram: 100.0,
        kalori: 187.0,
        lemak: 6.0,
        karbohidrat: 22.6,
        protein: 13.0,
        id_jenis_pangan: 7,
        id_takaran: 2,
        referensi_urt: "2 potong besar",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 102,
        nama_pangan: "Hasil lain dari kacang-kacangan",
        gram: 100.0,
        kalori: 228.4,
        lemak: 10.45,
        karbohidrat: 43.2,
        protein: 16.15,
        id_jenis_pangan: 7,
        id_takaran: 2,
        referensi_urt: "Ons",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 103,
        nama_pangan: "Jeruk, jeruk bali",
        gram: 1000.0,
        kalori: 311.3,
        lemak: 1.6,
        karbohidrat: 78.3,
        protein: 5.29,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "1 potong",
        referensi_gram_berat: 105,
      },
      {
        id_pangan: 104,
        nama_pangan: "Mangga",
        gram: 1000.0,
        kalori: 365.3,
        lemak: 1.3,
        karbohidrat: 95.03,
        protein: 3.64,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "3/4 buah besar",
        referensi_gram_berat: 90,
      },
      {
        id_pangan: 105,
        nama_pangan: "Apel",
        gram: 1000.0,
        kalori: 484.5,
        lemak: 3.4,
        karbohidrat: 108.8,
        protein: 4.25,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "1 buah kecil",
        referensi_gram_berat: 85,
      },
      {
        id_pangan: 106,
        nama_pangan: "Rambutan",
        gram: 1000.0,
        kalori: 276.0,
        lemak: 0.4,
        karbohidrat: 72.4,
        protein: 3.6,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "8 buah",
        referensi_gram_berat: 75,
      },
      {
        id_pangan: 107,
        nama_pangan: "Duku, langsat",
        gram: 1000.0,
        kalori: 403.2,
        lemak: 1.28,
        karbohidrat: 103.04,
        protein: 6.4,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "10-16 buah sedang",
        referensi_gram_berat: 80,
      },
      {
        id_pangan: 108,
        nama_pangan: "Durian",
        gram: 1000.0,
        kalori: 294.8,
        lemak: 6.6,
        karbohidrat: 61.6,
        protein: 5.5,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "2 biji besar",
        referensi_gram_berat: 35,
      },
      {
        id_pangan: 109,
        nama_pangan: "Salak",
        gram: 1000.0,
        kalori: 1350.6,
        lemak: 1.64,
        karbohidrat: 329.62,
        protein: 4.68,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "1 buah sedang",
        referensi_gram_berat: 65,
      },
      {
        id_pangan: 110,
        nama_pangan: "Pisang ambon",
        gram: 1000.0,
        kalori: 644.0,
        lemak: 2.1,
        karbohidrat: 168.0,
        protein: 7.0,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "1 buah sedang",
        referensi_gram_berat: 118,
      },
      {
        id_pangan: 111,
        nama_pangan: "Pisang lainnya",
        gram: 1000.0,
        kalori: 1131.1,
        lemak: 6.03,
        karbohidrat: 264.82,
        protein: 10.06,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "1 buah sedang",
        referensi_gram_berat: 95,
      },
      {
        id_pangan: 112,
        nama_pangan: "Pepaya",
        gram: 1000.0,
        kalori: 345.0,
        lemak: 0.0,
        karbohidrat: 91.5,
        protein: 3.75,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "1 potong besar",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 113,
        nama_pangan: "Semangka",
        gram: 1000.0,
        kalori: 128.8,
        lemak: 0.92,
        karbohidrat: 31.74,
        protein: 2.3,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "2 potong sedang",
        referensi_gram_berat: 180,
      },
      {
        id_pangan: 114,
        nama_pangan: "Tomat buah",
        gram: 1000.0,
        kalori: 240.0,
        lemak: 5.0,
        karbohidrat: 47.0,
        protein: 13.0,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "1 buah dengan diameter 6 cm",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 115,
        nama_pangan: "Alpukat",
        gram: 1000.0,
        kalori: 850.0,
        lemak: 65.0,
        karbohidrat: 77.0,
        protein: 9.0,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "1/2 buah besar",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 116,
        nama_pangan: "Jambu biji",
        gram: 1000.0,
        kalori: 490.0,
        lemak: 3.0,
        karbohidrat: 122.0,
        protein: 9.0,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "1 buah besar",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 117,
        nama_pangan: "Buah-buahan lainnya",
        gram: 1000.0,
        kalori: 383.98,
        lemak: 17.97,
        karbohidrat: 125.88,
        protein: 10.0,
        id_jenis_pangan: 8,
        id_takaran: 1,
        referensi_urt: "Kg",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 118,
        nama_pangan: "Minyak kelapa",
        gram: 800.0,
        kalori: 6960.0,
        lemak: 784.0,
        karbohidrat: 0.0,
        protein: 8.0,
        id_jenis_pangan: 9,
        id_takaran: 4,
        referensi_urt: "1 sendok teh",
        referensi_gram_berat: 4.6,
      },
      {
        id_pangan: 119,
        nama_pangan: "Minyak goreng (kelapa sawit, bunga matahari)",
        gram: 800.0,
        kalori: 7216.0,
        lemak: 88.0,
        karbohidrat: 0.0,
        protein: 0.0,
        id_jenis_pangan: 9,
        id_takaran: 4,
        referensi_urt: "1 sendok makan",
        referensi_gram_berat: 10.12,
      },
      {
        id_pangan: 120,
        nama_pangan: "Kelapa (tidak termasuk santan instan)",
        gram: 250.0,
        kalori: 1335.5,
        lemak: 130.12,
        karbohidrat: 52.1,
        protein: 12.65,
        id_jenis_pangan: 9,
        id_takaran: 3,
        referensi_urt: "Butir",
        referensi_gram_berat: 250,
      },
      {
        id_pangan: 121,
        nama_pangan: "Minyak dan kelapa lainnya",
        gram: 800.0,
        kalori: 6598.0,
        lemak: 810.0,
        karbohidrat: 0.0,
        protein: 13.5,
        id_jenis_pangan: 9,
        id_takaran: 4,
        referensi_urt: "Liter",
        referensi_gram_berat: 800,
      },
      {
        id_pangan: 122,
        nama_pangan: "Gula pasir",
        gram: 100.0,
        kalori: 364.0,
        lemak: 0.0,
        karbohidrat: 94.0,
        protein: 0.0,
        id_jenis_pangan: 10,
        id_takaran: 2,
        referensi_urt: "1 sendok makan ",
        referensi_gram_berat: 12.5,
      },
      {
        id_pangan: 123,
        nama_pangan: "Gula merah, gula air (pohom aren, kelapa, lontar)",
        gram: 100.0,
        kalori: 377.0,
        lemak: 10.0,
        karbohidrat: 85.5,
        protein: 3.0,
        id_jenis_pangan: 10,
        id_takaran: 2,
        referensi_urt: "1 sendok makan ",
        referensi_gram_berat: 10,
      },
      {
        id_pangan: 124,
        nama_pangan: "Teh bubuk",
        gram: 100.0,
        kalori: 132.0,
        lemak: 0.7,
        karbohidrat: 67.8,
        protein: 19.5,
        id_jenis_pangan: 10,
        id_takaran: 2,
        referensi_urt: "1 sendok makan ",
        referensi_gram_berat: 5.5,
      },
      {
        id_pangan: 125,
        nama_pangan: "Teh celup (sachet)",
        gram: 2.0,
        kalori: 2.64,
        lemak: 0.01,
        karbohidrat: 1.36,
        protein: 0.39,
        id_jenis_pangan: 10,
        id_takaran: 15,
        referensi_urt: "Kantong Celup",
        referensi_gram_berat: 2,
      },
      {
        id_pangan: 126,
        nama_pangan: "Kopi (bubuk, biji)",
        gram: 100.0,
        kalori: 352.0,
        lemak: 1.3,
        karbohidrat: 69.0,
        protein: 17.4,
        id_jenis_pangan: 10,
        id_takaran: 2,
        referensi_urt: "1 sendok makan ",
        referensi_gram_berat: 15,
      },
      {
        id_pangan: 127,
        nama_pangan: "Kopi instan (sachet)",
        gram: 20.0,
        kalori: 90.0,
        lemak: 15.0,
        karbohidrat: 17.0,
        protein: 1.0,
        id_jenis_pangan: 10,
        id_takaran: 16,
        referensi_urt: "Saset",
        referensi_gram_berat: 20,
      },
      {
        id_pangan: 128,
        nama_pangan: "Bahan minuman lainnya",
        gram: 100.0,
        kalori: 666.5,
        lemak: 0.0,
        karbohidrat: 0.0,
        protein: 8.17,
        id_jenis_pangan: 10,
        id_takaran: 2,
        referensi_urt: "ons",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 129,
        nama_pangan: "Garam",
        gram: 1.0,
        kalori: 0.0,
        lemak: 0.0,
        karbohidrat: 0.0,
        protein: 0.0,
        id_jenis_pangan: 12,
        id_takaran: 5,
        referensi_urt: "1 sendok teh",
        referensi_gram_berat: 4.2,
      },
      {
        id_pangan: 130,
        nama_pangan: "Kemiri",
        gram: 1.0,
        kalori: 6.36,
        lemak: 0.63,
        karbohidrat: 0.08,
        protein: 0.19,
        id_jenis_pangan: 12,
        id_takaran: 5,
        referensi_urt: "1 biji",
        referensi_gram_berat: 10,
      },
      {
        id_pangan: 131,
        nama_pangan: "Ketumbar/jinten",
        gram: 1.0,
        kalori: 4.04,
        lemak: 0.16,
        karbohidrat: 0.54,
        protein: 0.14,
        id_jenis_pangan: 12,
        id_takaran: 5,
        referensi_urt: "1 sendok teh",
        referensi_gram_berat: 5,
      },
      {
        id_pangan: 132,
        nama_pangan: "Merica/lada",
        gram: 1.0,
        kalori: 3.59,
        lemak: 0.07,
        karbohidrat: 0.64,
        protein: 0.12,
        id_jenis_pangan: 12,
        id_takaran: 5,
        referensi_urt: "1 sendok teh",
        referensi_gram_berat: 5,
      },
      {
        id_pangan: 133,
        nama_pangan: "Jahe",
        gram: 1.0,
        kalori: 0.51,
        lemak: 0.01,
        karbohidrat: 0.1,
        protein: 0.02,
        id_jenis_pangan: 12,
        id_takaran: 5,
        referensi_urt: "1 ruas jempol",
        referensi_gram_berat: 4,
      },
      {
        id_pangan: 134,
        nama_pangan: "Kunyit",
        gram: 1.0,
        kalori: 0.69,
        lemak: 0.03,
        karbohidrat: 0.09,
        protein: 0.02,
        id_jenis_pangan: 12,
        id_takaran: 5,
        referensi_urt: "1 ruas jempol",
        referensi_gram_berat: 4,
      },
      {
        id_pangan: 135,
        nama_pangan: "Asam",
        gram: 1.0,
        kalori: 1.32,
        lemak: 0.01,
        karbohidrat: 0.31,
        protein: 0.01,
        id_jenis_pangan: 12,
        id_takaran: 5,
        referensi_urt: "1 sendok makan",
        referensi_gram_berat: 15,
      },
      {
        id_pangan: 136,
        nama_pangan: "Terasi/petis",
        gram: 1.0,
        kalori: 2.5,
        lemak: 0.02,
        karbohidrat: 0.35,
        protein: 0.23,
        id_jenis_pangan: 12,
        id_takaran: 5,
        referensi_urt: "1 sendok makan",
        referensi_gram_berat: 15,
      },
      {
        id_pangan: 137,
        nama_pangan: "Kecap",
        gram: 100.0,
        kalori: 36.79,
        lemak: 1.04,
        karbohidrat: 7.2,
        protein: 4.56,
        id_jenis_pangan: 12,
        id_takaran: 17,
        referensi_urt: "Botol Kecil",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 138,
        nama_pangan: "Penyedap masakan/vetsin",
        gram: 1.0,
        kalori: 0.0,
        lemak: 0.0,
        karbohidrat: 0.0,
        protein: 0.0,
        id_jenis_pangan: 12,
        id_takaran: 5,
        referensi_urt: "Gram",
        referensi_gram_berat: 1,
      },
      {
        id_pangan: 139,
        nama_pangan: "Sambal jadi",
        gram: 100.0,
        kalori: 78.43,
        lemak: 0.32,
        karbohidrat: 19.6,
        protein: 1.6,
        id_jenis_pangan: 12,
        id_takaran: 17,
        referensi_urt: "Botol Kecil",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 140,
        nama_pangan: "Saus tomat",
        gram: 100.0,
        kalori: 78.43,
        lemak: 0.32,
        karbohidrat: 19.6,
        protein: 1.6,
        id_jenis_pangan: 12,
        id_takaran: 17,
        referensi_urt: "Botol Kecil",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 141,
        nama_pangan: "Bumbu maskan jadi/kemasan, bumbu racikan",
        gram: 1.0,
        kalori: 0.0,
        lemak: 0.0,
        karbohidrat: 0.0,
        protein: 0.0,
        id_jenis_pangan: 12,
        id_takaran: 5,
        referensi_urt: "Gram",
        referensi_gram_berat: 1,
      },
      {
        id_pangan: 142,
        nama_pangan: "Bumbu dapur lainnya (pala, jahe, kunyit, dsb.)",
        gram: 1.0,
        kalori: 0.49,
        lemak: 0.02,
        karbohidrat: 0.08,
        protein: 0.02,
        id_jenis_pangan: 12,
        id_takaran: 5,
        referensi_urt: "Gram",
        referensi_gram_berat: 1,
      },
      {
        id_pangan: 143,
        nama_pangan: "Mie instan",
        gram: 80.0,
        kalori: 356.0,
        lemak: 13.6,
        karbohidrat: 48.0,
        protein: 8.0,
        id_jenis_pangan: 13,
        id_takaran: 14,
        referensi_urt: "Bungkus",
        referensi_gram_berat: 80,
      },
      {
        id_pangan: 144,
        nama_pangan: "Kerupuk",
        gram: 100.0,
        kalori: 453.0,
        lemak: 17.85,
        karbohidrat: 69.15,
        protein: 3.88,
        id_jenis_pangan: 13,
        id_takaran: 2,
        referensi_urt: "3 biji sedang",
        referensi_gram_berat: 30,
      },
      {
        id_pangan: 145,
        nama_pangan: "Bubur bayi kemasan",
        gram: 150.0,
        kalori: 277.1,
        lemak: 5.1,
        karbohidrat: 47.84,
        protein: 9.96,
        id_jenis_pangan: 13,
        id_takaran: 12,
        referensi_urt: "Kotak",
        referensi_gram_berat: 150,
      },
      {
        id_pangan: 146,
        nama_pangan: "Roti tawar",
        gram: 150.0,
        kalori: 248.5,
        lemak: 1.35,
        karbohidrat: 49.85,
        protein: 7.95,
        id_jenis_pangan: 14,
        id_takaran: 6,
        referensi_urt: "Potong",
        referensi_gram_berat: 150,
      },
      {
        id_pangan: 147,
        nama_pangan: "Roti manis, roti lainnya",
        gram: 30.0,
        kalori: 161.5,
        lemak: 5.75,
        karbohidrat: 25.05,
        protein: 2.45,
        id_jenis_pangan: 14,
        id_takaran: 6,
        referensi_urt: "Potong",
        referensi_gram_berat: 30,
      },
      {
        id_pangan: 148,
        nama_pangan: "Kue kering, biskuit, semprong",
        gram: 100.0,
        kalori: 426.3,
        lemak: 13.02,
        karbohidrat: 72.24,
        protein: 6.19,
        id_jenis_pangan: 14,
        id_takaran: 2,
        referensi_urt: "Ons",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 149,
        nama_pangan: "Kue basah (kue lapis, bika ambon, lemper, dsb)",
        gram: 30.0,
        kalori: 137.5,
        lemak: 2.91,
        karbohidrat: 25.91,
        protein: 1.96,
        id_jenis_pangan: 14,
        id_takaran: 7,
        referensi_urt: "Buah",
        referensi_gram_berat: 30,
      },
      {
        id_pangan: 150,
        nama_pangan: "Makanan gorengan (tahu, tempe, bakwan, pisang)",
        gram: 40.0,
        kalori: 94.3,
        lemak: 6.16,
        karbohidrat: 7.06,
        protein: 3.62,
        id_jenis_pangan: 14,
        id_takaran: 6,
        referensi_urt: "Potong",
        referensi_gram_berat: 40,
      },
      {
        id_pangan: 151,
        nama_pangan: "Makanan gorengan lainnya",
        gram: 40.0,
        kalori: 181.0,
        lemak: 10.35,
        karbohidrat: 18.02,
        protein: 4.94,
        id_jenis_pangan: 14,
        id_takaran: 6,
        referensi_urt: "Potong",
        referensi_gram_berat: 40,
      },
      {
        id_pangan: 152,
        nama_pangan: "Bubur kacang hijau",
        gram: 200.0,
        kalori: 109.0,
        lemak: 0.5,
        karbohidrat: 18.3,
        protein: 8.7,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 200,
      },
      {
        id_pangan: 153,
        nama_pangan: "Gado-gado, ketoprak, pecel",
        gram: 250.0,
        kalori: 290.0,
        lemak: 10.9,
        karbohidrat: 34.0,
        protein: 14.0,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 250,
      },
      {
        id_pangan: 154,
        nama_pangan: "Nasi campur/rames",
        gram: 500.0,
        kalori: 583.6,
        lemak: 9.07,
        karbohidrat: 103.62,
        protein: 19.42,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 500,
      },
      {
        id_pangan: 155,
        nama_pangan: "Nasi goreng",
        gram: 250.0,
        kalori: 552.0,
        lemak: 6.4,
        karbohidrat: 60.4,
        protein: 6.4,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 250,
      },
      {
        id_pangan: 156,
        nama_pangan: "Nasi putih",
        gram: 200.0,
        kalori: 391.6,
        lemak: 0.22,
        karbohidrat: 89.32,
        protein: 4.62,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 200,
      },
      {
        id_pangan: 157,
        nama_pangan: "Lontong/ketupat sayur",
        gram: 350.0,
        kalori: 263.8,
        lemak: 5.2,
        karbohidrat: 47.0,
        protein: 5.93,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 350,
      },
      {
        id_pangan: 158,
        nama_pangan: "Soto, gule, sop, rawon, cincang",
        gram: 250.0,
        kalori: 143.7,
        lemak: 7.96,
        karbohidrat: 9.11,
        protein: 8.92,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 250,
      },
      {
        id_pangan: 159,
        nama_pangan: "Sayur matang (ditumis, disantan, dsb)",
        gram: 250.0,
        kalori: 232.5,
        lemak: 8.02,
        karbohidrat: 30.04,
        protein: 9.62,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 250,
      },
      {
        id_pangan: 160,
        nama_pangan: "Sate, tongseng",
        gram: 25.0,
        kalori: 89.5,
        lemak: 1.75,
        karbohidrat: 6.65,
        protein: 11.25,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi (5 tusuk)",
        referensi_gram_berat: 25,
      },
      {
        id_pangan: 161,
        nama_pangan: "Mie bakso, mie rebus, mie goreng",
        gram: 250.0,
        kalori: 529.0,
        lemak: 22.1,
        karbohidrat: 70.8,
        protein: 6.82,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 250,
      },
      {
        id_pangan: 162,
        nama_pangan: "Mie instan",
        gram: 250.0,
        kalori: 356.0,
        lemak: 13.6,
        karbohidrat: 48.0,
        protein: 8.0,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 250,
      },
      {
        id_pangan: 163,
        nama_pangan: "Makanan ringan anak-anak, krupuk/kripik",
        gram: 100.0,
        kalori: 509.1,
        lemak: 23.32,
        karbohidrat: 60.4,
        protein: 6.28,
        id_jenis_pangan: 14,
        id_takaran: 2,
        referensi_urt: "Ons",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 164,
        nama_pangan: "Ikan matang",
        gram: 75.0,
        kalori: 624.0,
        lemak: 35.85,
        karbohidrat: 0.0,
        protein: 70.35,
        id_jenis_pangan: 14,
        id_takaran: 6,
        referensi_urt: "Potong",
        referensi_gram_berat: 75,
      },
      {
        id_pangan: 165,
        nama_pangan: "Ayam/bebek/daging matang (ayam goreng, rendang, dsb)",
        gram: 150.0,
        kalori: 490.0,
        lemak: 22.8,
        karbohidrat: 0.6,
        protein: 66.2,
        id_jenis_pangan: 14,
        id_takaran: 6,
        referensi_urt: "Potong",
        referensi_gram_berat: 150,
      },
      {
        id_pangan: 166,
        nama_pangan: "Daging olahan (sosis, nugget, daging asap, dsb) matang",
        gram: 100.0,
        kalori: 340.0,
        lemak: 3.55,
        karbohidrat: 1.1,
        protein: 11.05,
        id_jenis_pangan: 14,
        id_takaran: 6,
        referensi_urt: "Potong",
        referensi_gram_berat: 100,
      },
      {
        id_pangan: 167,
        nama_pangan: "Bubur ayam",
        gram: 125.0,
        kalori: 203.75,
        lemak: 6.58,
        karbohidrat: 28.06,
        protein: 7.43,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 125,
      },
      {
        id_pangan: 168,
        nama_pangan: "Siomay, batagor",
        gram: 125.0,
        kalori: 203.75,
        lemak: 6.58,
        karbohidrat: 28.06,
        protein: 7.43,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 125,
      },
      {
        id_pangan: 169,
        nama_pangan: "Makanan jadi lainnya",
        gram: 30.0,
        kalori: 246.3,
        lemak: 11.29,
        karbohidrat: 24.2,
        protein: 8.9,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 30,
      },
      {
        id_pangan: 170,
        nama_pangan: "Air kemasan",
        gram: 520.0,
        kalori: 0.0,
        lemak: 0.0,
        karbohidrat: 0.0,
        protein: 0.0,
        id_jenis_pangan: 14,
        id_takaran: 4,
        referensi_urt: "Liter",
        referensi_gram_berat: 520,
      },
      {
        id_pangan: 171,
        nama_pangan: "Air kemasan galon",
        gram: 1000.0,
        kalori: 0.0,
        lemak: 0.0,
        karbohidrat: 0.0,
        protein: 0.0,
        id_jenis_pangan: 14,
        id_takaran: 9,
        referensi_urt: "Galon",
        referensi_gram_berat: 1000,
      },
      {
        id_pangan: 172,
        nama_pangan: "Air teh kemasan, minuman bersoda/mengandung CO2",
        gram: 200.0,
        kalori: 68.13,
        lemak: 0.0,
        karbohidrat: 0.0,
        protein: 0.0,
        id_jenis_pangan: 14,
        id_takaran: 12,
        referensi_urt: "Kotak (250ml)",
        referensi_gram_berat: 200,
      },
      {
        id_pangan: 173,
        nama_pangan: "Sari buah kemasan, minuman kesehatan, minuman berenergi",
        gram: 160.0,
        kalori: 72.53,
        lemak: 0.0,
        karbohidrat: 0.0,
        protein: 0.0,
        id_jenis_pangan: 14,
        id_takaran: 12,
        referensi_urt: "Kotak (200ml)",
        referensi_gram_berat: 160,
      },
      {
        id_pangan: 174,
        nama_pangan: "Minuman jadi(kopi, kopi susu, teh, susu coklat, dsb)",
        gram: 208.0,
        kalori: 61.0,
        lemak: 3.5,
        karbohidrat: 4.3,
        protein: 3.2,
        id_jenis_pangan: 14,
        id_takaran: 10,
        referensi_urt: "Gelas",
        referensi_gram_berat: 208,
      },
      {
        id_pangan: 175,
        nama_pangan: "Es krim",
        gram: 50.0,
        kalori: 207.0,
        lemak: 12.5,
        karbohidrat: 20.6,
        protein: 4.0,
        id_jenis_pangan: 14,
        id_takaran: 11,
        referensi_urt: "Mangkok kecil",
        referensi_gram_berat: 50,
      },
      {
        id_pangan: 176,
        nama_pangan: "Es lainnya",
        gram: 200.0,
        kalori: 56.0,
        lemak: 0.0,
        karbohidrat: 14.1,
        protein: 0.0,
        id_jenis_pangan: 14,
        id_takaran: 8,
        referensi_urt: "Porsi",
        referensi_gram_berat: 200,
      },
      {
        id_pangan: 177,
        nama_pangan: "Minuman keras",
        gram: 800.0,
        kalori: 384.0,
        lemak: 0.0,
        karbohidrat: 35.19,
        protein: 4.81,
        id_jenis_pangan: 14,
        id_takaran: 4,
        referensi_urt: "Liter",
        referensi_gram_berat: 800,
      },
    ],
  });
}

seed()
  .then(() => {
    console.log("✅ Seed data pangan selesai.");
  })
  .catch((err: unknown) => {
    console.error(`❌ Terjadi kesalahan saat mengisi data pangan: ${err}`);
    process.exit(1);
  });